import type { Theme } from './vscode-dark.theme'

export const jetbrainsLightTheme: Theme = {
  '--background': '#ffffff',
  '--contrast-active-border': '#f38518',
  '--contrast-border': '#6fc3df',
  '--focus-border': '#007fd4',
  '--foreground': '#4b4b4b',
  '--scrollbar-slider-background': '#d4d4d4',
  '--scrollbar-slider-hover-background': '#c4c4c4',
  '--scrollbar-slider-active-background': '#b4b4b4',
  '--badge-background': '#e0e0e0',
  '--badge-foreground': '#4b4b4b',
  '--button-border': 'transparent',
  '--button-icon-background': 'transparent',
  '--button-icon-hover-background': 'rgba(90, 93, 94, 0.31)',
  '--button-primary-background': '#f0f0f0',
  '--button-primary-foreground': '#4b4b4b',
  '--button-primary-hover-background': '#e0e0e0',
  '--button-secondary-background': '#f2f2f2',
  '--button-secondary-foreground': '#4b4b4b',
  '--button-secondary-hover-background': '#e2e2e2',
  '--checkbox-background': '#f0f0f0',
  '--checkbox-border': '#f0f0f0',
  '--checkbox-foreground': '#4b4b4b',
  '--list-active-selection-background': '#d4e2f0',
  '--list-active-selection-foreground': '#4b4b4b',
  '--list-hover-background': '#f2f2f2',
  '--divider-background': '#f2f2f2',
  '--dropdown-background': '#f0f0f0',
  '--dropdown-border': '#f0f0f0',
  '--dropdown-foreground': '#4b4b4b',
  '--input-background': '#f0f0f0',
  '--input-foreground': '#4b4b4b',
  '--input-placeholder-foreground': '#a9b7c6',
  '--link-active-foreground': '#6897bb',
  '--link-foreground': '#6897bb',
  '--progress-background': '#6897bb',
  '--panel-tab-active-border': '#4b4b4b',
  '--panel-tab-active-foreground': '#4b4b4b',
  '--panel-tab-foreground': '#4b4b4b99',
  '--panel-view-background': '#ffffff',
  '--panel-view-border': '#80808059',
}
