import type { Theme } from './vscode-dark.theme'

export const jetbrainsDarkTheme: Theme = {
  '--background': '#2b2b2b',
  '--contrast-active-border': '#f38518',
  '--contrast-border': '#6fc3df',
  '--focus-border': '#007fd4',
  '--foreground': '#a9b7c6',
  '--scrollbar-slider-background': '#515151',
  '--scrollbar-slider-hover-background': '#626262',
  '--scrollbar-slider-active-background': '#6e6e6e',
  '--badge-background': '#4e4e4e',
  '--badge-foreground': '#ffffff',
  '--button-border': 'transparent',
  '--button-icon-background': 'transparent',
  '--button-icon-hover-background': 'rgba(90, 93, 94, 0.31)',
  '--button-primary-background': '#3d3d3d',
  '--button-primary-foreground': '#ffffff',
  '--button-primary-hover-background': '#4e4e4e',
  '--button-secondary-background': '#3c3f41',
  '--button-secondary-foreground': '#ffffff',
  '--button-secondary-hover-background': '#4a4d4f',
  '--checkbox-background': '#3c3c3c',
  '--checkbox-border': '#3c3c3c',
  '--checkbox-foreground': '#a9b7c6',
  '--list-active-selection-background': '#214283',
  '--list-active-selection-foreground': '#ffffff',
  '--list-hover-background': '#3c3f41',
  '--divider-background': '#3c3f41',
  '--dropdown-background': '#3c3c3c',
  '--dropdown-border': '#3c3c3c',
  '--dropdown-foreground': '#a9b7c6',
  '--input-background': '#3c3c3c',
  '--input-foreground': '#a9b7c6',
  '--input-placeholder-foreground': '#a9b7c6',
  '--link-active-foreground': '#6897bb',
  '--link-foreground': '#6897bb',
  '--progress-background': '#6897bb',
  '--panel-tab-active-border': '#a9b7c6',
  '--panel-tab-active-foreground': '#a9b7c6',
  '--panel-tab-foreground': '#a9b7c699',
  '--panel-view-background': '#2b2b2b',
  '--panel-view-border': '#80808059',
} as const
