import type { Theme } from './vscode-dark.theme'

export const vscodeLightTheme: Theme = {
  '--background': '#ffffff',
  '--contrast-active-border': '#f38518',
  '--contrast-border': '#6fc3df',
  '--focus-border': '#007fd4',
  '--foreground': '#333333',
  '--scrollbar-slider-background': '#79797966',
  '--scrollbar-slider-hover-background': '#646464b3',
  '--scrollbar-slider-active-background': '#bfbfbf66',
  '--badge-background': '#c4c4c4',
  '--badge-foreground': '#ffffff',
  '--button-border': 'transparent',
  '--button-icon-background': 'transparent',
  '--button-icon-hover-background': 'rgba(90, 93, 94, 0.31)',
  '--button-primary-background': '#0e639c',
  '--button-primary-foreground': '#ffffff',
  '--button-primary-hover-background': '#1177bb',
  '--button-secondary-background': '#f3f3f3',
  '--button-secondary-foreground': '#333333',
  '--button-secondary-hover-background': '#e6e6e6',
  '--checkbox-background': '#f3f3f3',
  '--checkbox-border': '#f3f3f3',
  '--checkbox-foreground': '#333333',
  '--list-active-selection-background': '#007acc',
  '--list-active-selection-foreground': '#ffffff',
  '--list-hover-background': '#f0f0f0',
  '--divider-background': '#e1e4e5',
  '--dropdown-background': '#f3f3f3',
  '--dropdown-border': '#f3f3f3',
  '--dropdown-foreground': '#333333',
  '--input-background': '#f3f3f3',
  '--input-foreground': '#333333',
  '--input-placeholder-foreground': '#cccccc',
  '--link-active-foreground': '#3794ff',
  '--link-foreground': '#3794ff',
  '--progress-background': '#0e70c0',
  '--panel-tab-active-border': '#333333',
  '--panel-tab-active-foreground': '#333333',
  '--panel-tab-foreground': '#33333399',
  '--panel-view-background': '#ffffff',
  '--panel-view-border': '#80808059',
}
