const sidebar = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/examples',
      label: 'Examples',
    },
  ],
}

export default sidebar
